First branch
GraceHtet/hellomicroverse pull request #1
Opened 2022-11-29 13:15 UTC by GraceHtet

to view my first pull request

2022-11-29 13:40 UTC, franclobo requested changes
Hi @GraceHtet, 

Good job so far!
You did it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Correct Github flow ✔️ 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Kindly all main headers from the [README template](https://github.com/microverseinc/readme-template) should be present in your repo.
- [ ] Please 🙏🏽 remember to document your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
  - Kindly writhe a descriptive title and list the activities in your pull request 👇🏽 

| Your PR | Expected PR |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/204541439-a99c0642-e760-4d58-afdb-a4b2483e303e.png) | ![image](https://user-images.githubusercontent.com/58642949/204541354-3447f74a-003d-4629-96d7-43fb5bb92d2e.png) |

- [ ] Please follow these [steps](https://github.com/microverseinc/linters-config/tree/master/html-css) to install the linter and make sure that all of them are checked.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

## **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-29 13:40 UTC, franclobo commented on .gitignore
> +.github/workflow/linters.yml
- [ ] Please 🙏🏽 quit this folder from the .gitignore file. The linter should stay in the root folder.

2022-11-29 13:40 UTC, franclobo commented on .gitignore
> +test.md
- [ ] Kindly correct the path to the `test.md` file, we could use as follow 👉🏽 `./test.md` (**with a dot** at the beginning)

2022-11-29 13:40 UTC, franclobo commented on .gitignore
> +#node_modules
- [ ] Kindly correct the path to the `node_modules` folder, we could use as follow 👉🏽 `/node_modules` (**without a dot** at the beginning)

2022-11-29 15:26 UTC, GraceHtet commented
Fixed some mistakes in .gitignore
Added some contents to readme.md

2022-11-29 16:02 UTC, Alfredbis29 approved these changes
# STATUS: APPROVED  
 ## Hi @GraceHtet 
Your project is complete! There is nothing else to say other than... Great job clap Congratulations! :tada:
 
 TO HIGHLIGHT:
 
 * Your project is professional :white_check_mark:
 * Your repo is professional :white_check_mark:
 * Well structured files :white_check_mark:
 * No Linter errors :white_check_mark:
 * Use new readme template :white_check_mark: 
 
 Now you can merge this branch and move on :1st_place_medal: HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers four_leaf_clover:

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)
 
 ## Optional suggestions

- [ ] Kindly make sure to document your README professionally. Please use the [Microverse README template](https://github.com/microverseinc/readme-template) and customize it. as required by the previous review
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
Cheers and Happy coding! :clap:  :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-30 07:16 UTC, merged

2022-12-01 05:08 UTC, roshan-bajgain reviewed
Hi @GraceHtet, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, with hello-microverse PR but this is a `: Portfolio: setup and mobile first` re-review project. Please submit the correct URL.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._